#!/usr/bin/env bash
# Manual checklist for lab tests feature
# Run: bash tests/manual-checklist-lab-tests.sh
# Check each item manually in the browser at http://localhost:3000/tests

set -euo pipefail

echo "=== Lab Tests Feature — Manual Checklist ==="
echo ""
echo "Start the dev server: npm run dev"
echo "Navigate to: http://localhost:3000/tests"
echo ""
echo "--- List Page ---"
echo "[ ] Page loads with seeded lab tests (CBC, LIPID, VITD, UA, TSH, HBA1C)"
echo "[ ] Tests display code, name, price (as dollars), and turnaround hours"
echo "[ ] Tests are sorted alphabetically by name"
echo "[ ] Retired tests are hidden by default"
echo ""
echo "--- Search ---"
echo "[ ] Typing in search filters by code or name"
echo "[ ] Search is case-insensitive"
echo "[ ] Clearing search shows all tests"
echo "[ ] 'No lab tests found' empty state when no search results"
echo "[ ] 'No lab tests yet' with Add button when no tests exist"
echo ""
echo "--- Show Retired Toggle ---"
echo "[ ] Checking 'Show retired' reveals retired tests"
echo "[ ] Retired tests show 'Retired' badge"
echo "[ ] Retired test rows have muted text"
echo "[ ] Unchecking hides retired tests again"
echo ""
echo "--- Create ---"
echo "[ ] 'New Test' button opens dialog"
echo "[ ] URL changes to /tests?action=new"
echo "[ ] Code, Name, Price, Turnaround Hours fields present"
echo "[ ] All fields required"
echo "[ ] Submit with valid data creates test and closes dialog"
echo "[ ] New test appears in list without page reload"
echo "[ ] Code is auto-uppercased (type 'cbc' -> stored as 'CBC')"
echo "[ ] Duplicate code shows 'A lab test with this code already exists.'"
echo "[ ] Invalid price (e.g. 'abc') shows validation error"
echo "[ ] Zero or negative price rejected"
echo "[ ] Non-integer turnaround hours rejected"
echo "[ ] Button shows 'Saving...' while submitting"
echo ""
echo "--- Edit ---"
echo "[ ] Pencil button opens edit dialog"
echo "[ ] URL changes to /tests?edit=<id>"
echo "[ ] Form pre-fills with current values"
echo "[ ] Code field is disabled (read-only)"
echo "[ ] Price pre-fills correctly (e.g. '30.00' not '30')"
echo "[ ] Updating fields and saving reflects changes immediately"
echo "[ ] CRITICAL: Edit a test with price >= \$1000 — should pre-fill and save correctly"
echo ""
echo "--- Retire ---"
echo "[ ] Archive icon retires an active test"
echo "[ ] Test disappears from default view (becomes inactive)"
echo "[ ] Test appears when 'Show retired' is checked"
echo "[ ] Retiring a nonexistent test shows error alert"
echo ""
echo "--- Reactivate ---"
echo "[ ] With 'Show retired' on, rotate icon reactivates a retired test"
echo "[ ] Test reappears in default view"
echo "[ ] Reactivating a nonexistent test shows error alert"
echo ""
echo "--- Error Handling ---"
echo "[ ] Server errors show generic message, not raw Prisma errors"
echo "[ ] Retire/reactivate failures show alert with error message"
echo ""
echo "=== End Checklist ==="
