#!/usr/bin/env bash
# Manual checklist for patients feature
# Run: bash tests/manual-checklist.sh
# Check each item manually in the browser at http://localhost:3000/patients

set -euo pipefail

echo "=== Patients Feature — Manual Checklist ==="
echo ""
echo "Start the dev server: npm run dev"
echo "Navigate to: http://localhost:3000/patients"
echo ""
echo "--- List Page ---"
echo "[ ] Page loads with seeded patients (Garcia, Chen, Thompson)"
echo "[ ] Names display as 'Last, First' format"
echo "[ ] Date of birth displays in readable format (e.g. 'Mar 14, 1985')"
echo "[ ] Phone shows number or em-dash when missing"
echo "[ ] Email shows address or em-dash when missing"
echo "[ ] Clicking a row navigates to /patients/<id> detail page"
echo ""
echo "--- Search ---"
echo "[ ] Typing in search box filters patients by first or last name"
echo "[ ] Search is case-insensitive"
echo "[ ] Clearing search shows all patients"
echo "[ ] When no results match, 'No patients found' empty state appears"
echo "[ ] When no patients exist at all, 'No patients yet' with Add button appears"
echo ""
echo "--- Create ---"
echo "[ ] 'New Patient' button opens dialog with empty form"
echo "[ ] URL changes to /patients?action=new"
echo "[ ] First name and last name are required (browser validation)"
echo "[ ] Date of birth is required"
echo "[ ] Submitting with valid data creates patient and closes dialog"
echo "[ ] New patient appears in list without page reload"
echo "[ ] Submitting with future DOB shows 'Date of birth must be in the past'"
echo "[ ] Submitting without any contact method shows Zod validation error"
echo "[ ] Button shows 'Saving...' while submitting"
echo "[ ] Closing dialog (X or overlay click) returns to /patients"
echo ""
echo "--- Edit ---"
echo "[ ] Edit button on detail page navigates to /patients?edit=<id>"
echo "[ ] Dialog opens with patient data pre-filled"
echo "[ ] Date of birth pre-fills correctly (no off-by-one day shift)"
echo "[ ] Updating fields and saving reflects changes immediately"
echo "[ ] Error handling works same as create"
echo ""
echo "--- Detail Page ---"
echo "[ ] /patients/<id> shows patient detail with two cards"
echo "[ ] Header shows name as 'Last, First'"
echo "[ ] Personal Info card shows name as 'Last, First' (consistent with header)"
echo "[ ] Contact info shows 'Not provided' for missing phone/email"
echo "[ ] Back link returns to /patients"
echo "[ ] Edit button navigates to list with edit dialog open"
echo "[ ] /patients/nonexistent-id shows 404 page"
echo ""
echo "--- Error Handling ---"
echo "[ ] Server errors show generic message, not raw Prisma errors"
echo ""
echo "=== End Checklist ==="
